apiVersion: api.deploy.scaler.com/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: deploy-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  # TODO(user): Add fields here
  start: 
  end: 19
  replicas: 3
  deploys:
    - name: abc
      namespace: default
    - name: def
      namespace: default